local keybinds = {
	debug_local = Enum.KeyCode.P,
	debug_server = Enum.KeyCode.M,
	slot_1 = Enum.KeyCode.One,
	slot_2 = Enum.KeyCode.Two,
	slot_3 = Enum.KeyCode.Three,
	slot_4 = Enum.KeyCode.Four,
	slot_5 = Enum.KeyCode.Five,
	slot_6 = Enum.KeyCode.Six,
	slot_7 = Enum.KeyCode.Seven,
	slot_8 = Enum.KeyCode.Eight,
	slot_9 = Enum.KeyCode.Nine,
	tablist = Enum.KeyCode.Tab,
	tool_switch = Enum.KeyCode.E,
}

return keybinds
